{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Signal Decomposer Comparison: Savitzky-Golay vs Butterworth\n",
    "\n",
    "This notebook demonstrates the redesigned `SignalDecomposer` class and compares the two filtering methods."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from signal_decomposer_v2 import SignalDecomposer, preprocess_for_forecast\n",
    "\n",
    "# Set style\n",
    "sns.set_style('whitegrid')\n",
    "plt.rcParams['figure.figsize'] = (15, 10)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Generate Synthetic Data\n",
    "\n",
    "Create a signal with multiple known frequency components:\n",
    "- Daily cycle (24 hour period)\n",
    "- Weekly cycle (7 day period)\n",
    "- Monthly cycle (28 day period)\n",
    "- Random noise"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate 6 months of 15-minute data\n",
    "np.random.seed(42)\n",
    "dates = pd.date_range('2023-01-01', '2023-07-01', freq='15min')\n",
    "n = len(dates)\n",
    "t = np.arange(n)\n",
    "\n",
    "# Frequency is 96 observations per day (24 hours * 4 obs/hour)\n",
    "freq = 96\n",
    "\n",
    "# Component amplitudes\n",
    "amp_daily = 10\n",
    "amp_weekly = 5\n",
    "amp_monthly = 3\n",
    "amp_noise = 0.5\n",
    "offset = 20\n",
    "\n",
    "# Create signal components\n",
    "daily_cycle = amp_daily * np.sin(2 * np.pi * t / freq)\n",
    "weekly_cycle = amp_weekly * np.sin(2 * np.pi * t / (freq * 7))\n",
    "monthly_cycle = amp_monthly * np.sin(2 * np.pi * t / (freq * 28))\n",
    "noise = amp_noise * np.random.randn(n)\n",
    "trend = offset + 0.01 * t  # Slight upward trend\n",
    "\n",
    "# Combine all components\n",
    "y = daily_cycle + weekly_cycle + monthly_cycle + noise + trend\n",
    "\n",
    "# Create DataFrame\n",
    "df = pd.DataFrame({\n",
    "    'ds': dates,\n",
    "    'y': y,\n",
    "    'daily_true': daily_cycle,\n",
    "    'weekly_true': weekly_cycle,\n",
    "    'monthly_true': monthly_cycle,\n",
    "    'noise_true': noise,\n",
    "    'trend_true': trend\n",
    "})\n",
    "\n",
    "print(f\"Generated {len(df)} observations over {len(df) / freq:.1f} days\")\n",
    "print(f\"\\nSignal components:\")\n",
    "print(f\"  Daily cycle: amplitude = {amp_daily}, period = 1 day\")\n",
    "print(f\"  Weekly cycle: amplitude = {amp_weekly}, period = 7 days\")\n",
    "print(f\"  Monthly cycle: amplitude = {amp_monthly}, period = 28 days\")\n",
    "print(f\"  Noise: std = {amp_noise}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Visualize Original Signal"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, axes = plt.subplots(5, 1, figsize=(15, 12))\n",
    "\n",
    "# Plot first 2 weeks\n",
    "plot_days = 14\n",
    "plot_n = plot_days * freq\n",
    "df_plot = df.iloc[:plot_n]\n",
    "\n",
    "axes[0].plot(df_plot['ds'], df_plot['y'], label='Combined Signal', alpha=0.8)\n",
    "axes[0].set_title('Combined Signal (First 14 Days)', fontsize=12, fontweight='bold')\n",
    "axes[0].set_ylabel('Value')\n",
    "axes[0].legend()\n",
    "\n",
    "axes[1].plot(df_plot['ds'], df_plot['daily_true'], label='Daily Cycle', color='orange')\n",
    "axes[1].set_title('Daily Cycle Component', fontsize=12)\n",
    "axes[1].set_ylabel('Value')\n",
    "axes[1].legend()\n",
    "\n",
    "axes[2].plot(df_plot['ds'], df_plot['weekly_true'], label='Weekly Cycle', color='green')\n",
    "axes[2].set_title('Weekly Cycle Component', fontsize=12)\n",
    "axes[2].set_ylabel('Value')\n",
    "axes[2].legend()\n",
    "\n",
    "axes[3].plot(df_plot['ds'], df_plot['monthly_true'], label='Monthly Cycle', color='purple')\n",
    "axes[3].set_title('Monthly Cycle Component', fontsize=12)\n",
    "axes[3].set_ylabel('Value')\n",
    "axes[3].legend()\n",
    "\n",
    "axes[4].plot(df_plot['ds'], df_plot['trend_true'], label='Trend', color='red')\n",
    "axes[4].set_title('Trend Component', fontsize=12)\n",
    "axes[4].set_ylabel('Value')\n",
    "axes[4].set_xlabel('Date')\n",
    "axes[4].legend()\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Apply Savitzky-Golay Decomposition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define periods\n",
    "periods_days = [1, 3, 7, 14, 28]\n",
    "\n",
    "# Create decomposer with Savitzky-Golay\n",
    "decomposer_sg = SignalDecomposer(\n",
    "    freq=freq,\n",
    "    periods_days=periods_days,\n",
    "    filter_type='savgol',\n",
    "    savgol_polyorder=3,\n",
    "    savgol_mode='nearest'\n",
    ")\n",
    "\n",
    "# Decompose\n",
    "df_sg = decomposer_sg.decompose(df[['ds', 'y']].copy())\n",
    "\n",
    "# Show component info\n",
    "print(\"\\nComponent Information:\")\n",
    "print(decomposer_sg.get_component_info())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Apply Butterworth Decomposition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create decomposer with Butterworth\n",
    "decomposer_bw = SignalDecomposer(\n",
    "    freq=freq,\n",
    "    periods_days=periods_days,\n",
    "    filter_type='butterworth',\n",
    "    butter_order=4\n",
    ")\n",
    "\n",
    "# Decompose\n",
    "df_bw = decomposer_bw.decompose(df[['ds', 'y']].copy())\n",
    "\n",
    "print(\"\\nComponent Information:\")\n",
    "print(decomposer_bw.get_component_info())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Compare Daily Cycle Extraction\n",
    "\n",
    "The daily cycle should be captured in the `y_p0` component (1-3 day band)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, axes = plt.subplots(3, 1, figsize=(15, 10))\n",
    "\n",
    "plot_days = 7\n",
    "plot_n = plot_days * freq\n",
    "\n",
    "# True daily component\n",
    "axes[0].plot(df.iloc[:plot_n]['ds'], df.iloc[:plot_n]['daily_true'], \n",
    "             label='True Daily Cycle', color='blue', linewidth=2)\n",
    "axes[0].set_title('True Daily Cycle (First 7 Days)', fontsize=12, fontweight='bold')\n",
    "axes[0].set_ylabel('Value')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Savitzky-Golay extraction\n",
    "axes[1].plot(df.iloc[:plot_n]['ds'], df.iloc[:plot_n]['daily_true'], \n",
    "             label='True', color='blue', alpha=0.5, linewidth=2)\n",
    "axes[1].plot(df_sg.iloc[:plot_n]['ds'], df_sg.iloc[:plot_n]['y_p0'], \n",
    "             label='Savitzky-Golay Extract', color='red', linewidth=2)\n",
    "axes[1].set_title('Savitzky-Golay: Daily Component (y_p0)', fontsize=12, fontweight='bold')\n",
    "axes[1].set_ylabel('Value')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "# Butterworth extraction\n",
    "axes[2].plot(df.iloc[:plot_n]['ds'], df.iloc[:plot_n]['daily_true'], \n",
    "             label='True', color='blue', alpha=0.5, linewidth=2)\n",
    "axes[2].plot(df_bw.iloc[:plot_n]['ds'], df_bw.iloc[:plot_n]['y_p0'], \n",
    "             label='Butterworth Extract', color='green', linewidth=2)\n",
    "axes[2].set_title('Butterworth: Daily Component (y_p0)', fontsize=12, fontweight='bold')\n",
    "axes[2].set_ylabel('Value')\n",
    "axes[2].set_xlabel('Date')\n",
    "axes[2].legend()\n",
    "axes[2].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Calculate errors\n",
    "error_sg = np.mean((df_sg['y_p0'].values - df.iloc[:len(df_sg)]['daily_true'].values) ** 2)\n",
    "error_bw = np.mean((df_bw['y_p0'].values - df.iloc[:len(df_bw)]['daily_true'].values) ** 2)\n",
    "print(f\"\\nMean Squared Error (Daily Cycle):\")\n",
    "print(f\"  Savitzky-Golay: {error_sg:.4f}\")\n",
    "print(f\"  Butterworth:    {error_bw:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Compare Weekly Cycle Extraction\n",
    "\n",
    "The weekly cycle should be captured in the `y_p2` component (7-14 day band)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, axes = plt.subplots(3, 1, figsize=(15, 10))\n",
    "\n",
    "plot_days = 28\n",
    "plot_n = plot_days * freq\n",
    "\n",
    "# True weekly component\n",
    "axes[0].plot(df.iloc[:plot_n]['ds'], df.iloc[:plot_n]['weekly_true'], \n",
    "             label='True Weekly Cycle', color='blue', linewidth=2)\n",
    "axes[0].set_title('True Weekly Cycle (First 28 Days)', fontsize=12, fontweight='bold')\n",
    "axes[0].set_ylabel('Value')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Savitzky-Golay extraction\n",
    "axes[1].plot(df.iloc[:plot_n]['ds'], df.iloc[:plot_n]['weekly_true'], \n",
    "             label='True', color='blue', alpha=0.5, linewidth=2)\n",
    "axes[1].plot(df_sg.iloc[:plot_n]['ds'], df_sg.iloc[:plot_n]['y_p2'], \n",
    "             label='Savitzky-Golay Extract', color='red', linewidth=2)\n",
    "axes[1].set_title('Savitzky-Golay: Weekly Component (y_p2)', fontsize=12, fontweight='bold')\n",
    "axes[1].set_ylabel('Value')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "# Butterworth extraction\n",
    "axes[2].plot(df.iloc[:plot_n]['ds'], df.iloc[:plot_n]['weekly_true'], \n",
    "             label='True', color='blue', alpha=0.5, linewidth=2)\n",
    "axes[2].plot(df_bw.iloc[:plot_n]['ds'], df_bw.iloc[:plot_n]['y_p2'], \n",
    "             label='Butterworth Extract', color='green', linewidth=2)\n",
    "axes[2].set_title('Butterworth: Weekly Component (y_p2)', fontsize=12, fontweight='bold')\n",
    "axes[2].set_ylabel('Value')\n",
    "axes[2].set_xlabel('Date')\n",
    "axes[2].legend()\n",
    "axes[2].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Calculate errors\n",
    "error_sg = np.mean((df_sg['y_p2'].values - df.iloc[:len(df_sg)]['weekly_true'].values) ** 2)\n",
    "error_bw = np.mean((df_bw['y_p2'].values - df.iloc[:len(df_bw)]['weekly_true'].values) ** 2)\n",
    "print(f\"\\nMean Squared Error (Weekly Cycle):\")\n",
    "print(f\"  Savitzky-Golay: {error_sg:.4f}\")\n",
    "print(f\"  Butterworth:    {error_bw:.4f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Compare All Components Side-by-Side"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get component names (excluding trend components)\n",
    "component_cols = ['y_high', 'y_p0', 'y_p1', 'y_p2', 'y_p3', 'y_trend']\n",
    "\n",
    "fig, axes = plt.subplots(len(component_cols), 2, figsize=(18, 15))\n",
    "fig.suptitle('Component Comparison: Savitzky-Golay vs Butterworth', \n",
    "             fontsize=14, fontweight='bold')\n",
    "\n",
    "plot_days = 14\n",
    "plot_n = min(plot_days * freq, len(df_sg), len(df_bw))\n",
    "\n",
    "for i, comp in enumerate(component_cols):\n",
    "    if comp in df_sg.columns:\n",
    "        # Savitzky-Golay\n",
    "        axes[i, 0].plot(df_sg.iloc[:plot_n]['ds'], df_sg.iloc[:plot_n][comp], \n",
    "                       color='red', linewidth=1.5)\n",
    "        axes[i, 0].set_title(f'{comp} - Savitzky-Golay', fontsize=10)\n",
    "        axes[i, 0].set_ylabel('Value')\n",
    "        axes[i, 0].grid(True, alpha=0.3)\n",
    "        \n",
    "        # Butterworth\n",
    "        axes[i, 1].plot(df_bw.iloc[:plot_n]['ds'], df_bw.iloc[:plot_n][comp], \n",
    "                       color='green', linewidth=1.5)\n",
    "        axes[i, 1].set_title(f'{comp} - Butterworth', fontsize=10)\n",
    "        axes[i, 1].set_ylabel('Value')\n",
    "        axes[i, 1].grid(True, alpha=0.3)\n",
    "\n",
    "axes[-1, 0].set_xlabel('Date')\n",
    "axes[-1, 1].set_xlabel('Date')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Spectral Analysis\n",
    "\n",
    "Use FFT to see which filter better isolates target frequencies."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from scipy.fft import fft, fftfreq\n",
    "\n",
    "def compute_spectrum(signal, sampling_rate):\n",
    "    \"\"\"Compute power spectrum of signal.\"\"\"\n",
    "    n = len(signal)\n",
    "    yf = fft(signal)\n",
    "    xf = fftfreq(n, 1/sampling_rate)[:n//2]\n",
    "    power = 2.0/n * np.abs(yf[0:n//2])\n",
    "    return xf, power\n",
    "\n",
    "# Compute spectra\n",
    "freq_hz = freq / (24 * 3600)  # Convert to Hz\n",
    "\n",
    "# Original signal\n",
    "f_orig, p_orig = compute_spectrum(df['y'].values, freq)\n",
    "\n",
    "# Daily component extractions\n",
    "f_sg, p_sg = compute_spectrum(df_sg['y_p0'].values, freq)\n",
    "f_bw, p_bw = compute_spectrum(df_bw['y_p0'].values, freq)\n",
    "f_true, p_true = compute_spectrum(df.iloc[:len(df_sg)]['daily_true'].values, freq)\n",
    "\n",
    "# Plot\n",
    "fig, axes = plt.subplots(2, 1, figsize=(15, 10))\n",
    "\n",
    "# Full spectrum\n",
    "axes[0].semilogy(f_orig, p_orig, label='Original Signal', alpha=0.7)\n",
    "axes[0].axvline(x=1, color='red', linestyle='--', label='Daily (1 cycle/day)', alpha=0.7)\n",
    "axes[0].axvline(x=1/7, color='green', linestyle='--', label='Weekly (1/7 cycle/day)', alpha=0.7)\n",
    "axes[0].set_title('Power Spectrum - Original Signal', fontsize=12, fontweight='bold')\n",
    "axes[0].set_xlabel('Frequency (cycles per day)')\n",
    "axes[0].set_ylabel('Power')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "axes[0].set_xlim([0, 5])\n",
    "\n",
    "# Daily component extraction\n",
    "axes[1].semilogy(f_true, p_true, label='True Daily Cycle', color='blue', linewidth=2, alpha=0.7)\n",
    "axes[1].semilogy(f_sg, p_sg, label='Savitzky-Golay Extract', color='red', linewidth=2, alpha=0.7)\n",
    "axes[1].semilogy(f_bw, p_bw, label='Butterworth Extract', color='green', linewidth=2, alpha=0.7)\n",
    "axes[1].axvline(x=1, color='black', linestyle='--', label='Target (1 cycle/day)', alpha=0.5)\n",
    "axes[1].set_title('Power Spectrum - Daily Component Extraction (y_p0)', fontsize=12, fontweight='bold')\n",
    "axes[1].set_xlabel('Frequency (cycles per day)')\n",
    "axes[1].set_ylabel('Power')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "axes[1].set_xlim([0, 5])\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Summary Statistics"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Calculate reconstruction error\n",
    "# y ≈ y_high + y_p0 + y_p1 + y_p2 + y_p3 + y_trend\n",
    "\n",
    "y_reconstructed_sg = (df_sg['y_high'] + df_sg['y_p0'] + df_sg['y_p1'] + \n",
    "                     df_sg['y_p2'] + df_sg['y_p3'] + df_sg['y_trend'])\n",
    "y_reconstructed_bw = (df_bw['y_high'] + df_bw['y_p0'] + df_bw['y_p1'] + \n",
    "                     df_bw['y_p2'] + df_bw['y_p3'] + df_bw['y_trend'])\n",
    "\n",
    "error_sg = np.mean((y_reconstructed_sg - df_sg['y']) ** 2)\n",
    "error_bw = np.mean((y_reconstructed_bw - df_bw['y']) ** 2)\n",
    "\n",
    "print(\"=\"*70)\n",
    "print(\"SUMMARY STATISTICS\")\n",
    "print(\"=\"*70)\n",
    "print(f\"\\nReconstruction Error (MSE):\")\n",
    "print(f\"  Savitzky-Golay: {error_sg:.6f}\")\n",
    "print(f\"  Butterworth:    {error_bw:.6f}\")\n",
    "\n",
    "# Component variance explained\n",
    "total_var = df['y'].var()\n",
    "\n",
    "print(f\"\\nVariance Explained by Components (Savitzky-Golay):\")\n",
    "for comp in component_cols:\n",
    "    if comp in df_sg.columns:\n",
    "        var_pct = (df_sg[comp].var() / total_var) * 100\n",
    "        print(f\"  {comp:12s}: {var_pct:6.2f}%\")\n",
    "\n",
    "print(f\"\\nVariance Explained by Components (Butterworth):\")\n",
    "for comp in component_cols:\n",
    "    if comp in df_bw.columns:\n",
    "        var_pct = (df_bw[comp].var() / total_var) * 100\n",
    "        print(f\"  {comp:12s}: {var_pct:6.2f}%\")\n",
    "\n",
    "print(\"\\n\" + \"=\"*70)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Conclusions\n",
    "\n",
    "### Savitzky-Golay Filter:\n",
    "- ✓ Better at preserving peak shapes\n",
    "- ✓ Smoother output\n",
    "- ✓ Less sensitive to noise\n",
    "- ✗ Not true frequency domain filtering\n",
    "- ✗ Edge effects with some boundary modes\n",
    "\n",
    "### Butterworth Filter:\n",
    "- ✓ True bandpass filtering\n",
    "- ✓ Precise frequency control\n",
    "- ✓ Good for isolating oscillations\n",
    "- ✗ Can introduce ringing\n",
    "- ✗ More sensitive to discontinuities\n",
    "\n",
    "### Recommendation:\n",
    "- **For temperature forecasting:** Use Savitzky-Golay (smoother trends)\n",
    "- **For periodic signal analysis:** Use Butterworth (precise frequency isolation)\n",
    "- **For exploratory analysis:** Try both and compare!"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
